name: TrollUltimateV1
version: 2.4
main: de.theredend2000.trollultimatev1.Main
api-version: 1.13
softdepend: [NoteBlockAPI]
commands:
  trollultimate:
    aliases:
      - tu
      - troll
      - trollu
      - tultimate
      - trollulti
    description: Open the troll menu
  test:
