name: TrollUltimateV1
version: 1.6
main: de.theredend2000.trollultimatev1.Main
api-version: 1.19
commands:
  trollultimate:
    aliases:
      - tu
      - troll
      - trollu
      - tultimate
      - trollulti
    description: Open the troll menu
