name: TrollUltimateV1
version: 2.2
main: de.theredend2000.trollultimatev1.Main
api-version: 1.19
softdepend: [NoteBlockAPI]
commands:
  trollultimate:
    aliases:
      - tu
      - troll
      - trollu
      - tultimate
      - trollulti
    description: Open the troll menu
  music:
